// SPDX-License-Identifier: CC-BY-SA-4.0
//
// Regenerates src/lib/__fixtures__/siemsene-engine-golden.json by running
// siemsene/beergame's OWN engine, so the parity test in
// src/lib/beerGameParity.test.ts compares against upstream's real numbers
// rather than against something hand-derived.
//
// Usage:
//   git clone --depth 1 https://github.com/siemsene/beergame.git /tmp/beergame
//   node scripts/generate-parity-fixture.mts /tmp/beergame
//
// Upstream is not vendored into this repo. The script copies the two engine
// files it needs into a scratch directory and patches their imports (Node's
// type-stripping loader needs explicit `.ts` extensions and `type` modifiers on
// type-only imports, neither of which upstream's source has). If upstream
// restructures those files, this patching is the first thing to check.

import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const upstream = process.argv[2];
if (!upstream) {
  console.error("usage: node scripts/generate-parity-fixture.mts <path-to-beergame-clone>");
  process.exit(1);
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = join(repoRoot, "src", "lib", "__fixtures__", "siemsene-engine-golden.json");

const scratch = mkdtempSync(join(tmpdir(), "beergame-parity-"));
for (const file of ["gameModel.ts", "gameEngine.ts"]) {
  copyFileSync(join(upstream, "src", "logic", file), join(scratch, file));
}

const patches: [string, string][] = [
  ['import { OrdersForWeek } from "./gameEngine";', 'import type { OrdersForWeek } from "./gameEngine.ts";'],
  [
    'import { GameConfig, TeamState, Role, ROLES } from "./gameModel";',
    'import { ROLES, type GameConfig, type TeamState, type Role } from "./gameModel.ts";',
  ],
];

for (const file of ["gameModel.ts", "gameEngine.ts"]) {
  const path = join(scratch, file);
  let src = readFileSync(path, "utf8");
  let patched = false;
  for (const [from, to] of patches) {
    if (src.includes(from)) {
      src = src.replace(from, to);
      patched = true;
    }
  }
  if (!patched) {
    console.warn(
      `warning: no import patch applied to ${file} — upstream may have changed; the import may fail to load`,
    );
  }
  writeFileSync(path, src);
}

const model = await import(pathToFileURL(join(scratch, "gameModel.ts")).href);
const engine = await import(pathToFileURL(join(scratch, "gameEngine.ts")).href);
const { createInitialTeamState, defaultConfig, ROLES } = model;
const { simulateWeek } = engine;

const ROUNDS = 40;
const CONSTANT_DEMAND = 8;

// Constant demand on purpose: upstream's simulateWeek indexes
// config.customerDemand[week] with a 1-based week and reads one element past the
// intended position. With every element equal that bug is unobservable, so the
// comparison isolates the pipeline mechanics — which is what we want to pin.
// Bruce's (correct) demand step is covered by its own tests.
const config = {
  ...defaultConfig(),
  nWeeks: ROUNDS,
  customerDemand: Array.from({ length: ROUNDS + 2 }, () => CONSTANT_DEMAND),
  extraOrderDelay: false,
  displayUpstreamBackorders: false,
};

// Deterministic, jagged orders so backlogs actually build.
let seed = 12345;
const rnd = () => {
  seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
  return seed / 4294967296;
};

const orders = Array.from({ length: ROUNDS }, () => ({
  retailer: Math.floor(rnd() * 17),
  wholesaler: Math.floor(rnd() * 17),
  distributor: Math.floor(rnd() * 17),
  factory: Math.floor(rnd() * 17),
}));

let team = createInitialTeamState("t1", "Reference");
for (let week = 1; week <= ROUNDS; week++) {
  team = simulateWeek(team, config, orders[week - 1]).nextTeam;
}

const rounds = Array.from({ length: ROUNDS }, (_, i) => {
  const byRole: Record<string, unknown> = { round: i + 1 };
  for (const role of ROLES as string[]) {
    const h = team.stages[role].history[i];
    byRole[role.toUpperCase()] = {
      incomingOrder: h.demandThisWeek,
      shipped: h.shipped,
      inventory: h.inventoryEnd,
      backlog: h.backlogEnd,
      cost: h.cost,
    };
  }
  return byRole;
});

const fixture = {
  _comment:
    "Generated by running siemsene/beergame's own src/logic/gameEngine.ts. Do not hand-edit — regenerate with scripts/generate-parity-fixture.mts. See NOTICE.md.",
  config: {
    holdingCost: config.inventoryCost,
    backorderCost: config.backlogCost,
    initialInventory: 12, // hardcoded in upstream's createStage()
    pipelineSeed: 4, // ditto (delay1 = delay2 = 4)
    constantDemand: CONSTANT_DEMAND,
    rounds: ROUNDS,
  },
  orders: orders.map((o) => ({
    RETAILER: o.retailer,
    WHOLESALER: o.wholesaler,
    DISTRIBUTOR: o.distributor,
    FACTORY: o.factory,
  })),
  rounds,
};

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${JSON.stringify(fixture, null, 2)}\n`);
console.log(`wrote ${outPath} (${rounds.length} rounds)`);
